version: '3'
services:
  registry:
    image: 'wkay/registry:v2'
    container_name: 'myrmi-registry'
    environment:
      RUN_COMPONENT: 'REGISTRY'

  server:
    image: 'wkay/server:v2'
    container_name: 'myrmi-server'
    depends_on:
      - registry
    environment:
      RUN_COMPONENT: 'SERVER'

  client:
    image: 'wkay/client:v2'
    container_name: 'myrmi-client'
    depends_on:
      - registry
      - server
    environment:
      RUN_COMPONENT: 'CLIENT'

